name: Scan with Detekt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
     - cron: '31 4 * * 3'
  workflow_dispatch:

env:
  DETEKT_VERSION: 1.23.6

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Detekt CLI
      run: |
        curl -sSLO https://github.com/detekt/detekt/releases/download/v${{ env.DETEKT_VERSION }}/detekt-cli-${{ env.DETEKT_VERSION }}-all.jar

    - name: Run Detekt
      continue-on-error: true
      run: |
        java -jar detekt-cli-${{ env.DETEKT_VERSION }}-all.jar \
          --input ${{ github.workspace }} \
          --config ${{ github.workspace }}/scripts/detekt/detekt_config.yml \
          --report sarif:${{ github.workspace }}/detekt.sarif.json

    - name: Make artifact location URIs relative
      continue-on-error: true
      run: |
        echo "$(
          jq \
            --arg github_workspace ${{ github.workspace }} \
            '. | ( .runs[].results[].locations[].physicalLocation.artifactLocation.uri |= if test($github_workspace) then .[($github_workspace | length | . + 1):] else . end )' \
            ${{ github.workspace }}/detekt.sarif.json
        )" > ${{ github.workspace }}/detekt.sarif.json

    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ github.workspace }}/detekt.sarif.json
        checkout_path: ${{ github.workspace }}
